// eslint-disable-next-line @typescript-eslint/no-var-requires
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  purge: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      white: '#fff',
      black: '#000',
      background: {
        code: 'var(--color-bg-code)'
      },
      text: {
        DEFAULT: 'var(--color-text)',
        muted: 'var(--color-text-muted)',
        code: 'var(--color-text-code)',
        hover: 'var(--color-text-hover)',
      },
      button: {
        bg: 'var(--color-button-bg)',
        border: 'var(--color-button-border)',
        hover: 'var(--color-button-hover)',
        text: 'var(--color-button-text)',
        textHover: 'var(--color-button-text-hover)',
      },
      input: {
        bg: 'var(--color-input-bg)',
        border: 'var(--color-input-border)',
        text: 'var(--color-input-text)',
      },
      gray: {
        100: 'var(--scale-gray-100)',
        200: 'var(--scale-gray-200)',
        300: 'var(--scale-gray-300)',
        400: 'var(--scale-gray-400)',
        500: 'var(--scale-gray-500)',
        600: 'var(--scale-gray-600)',
        700: 'var(--scale-gray-700)',
        800: 'var(--scale-gray-800)',
        900: 'var(--scale-gray-900)',
      },
      accent: {
        100: 'var(--scale-accent-100)',
        200: 'var(--scale-accent-200)',
        300: 'var(--scale-accent-300)',
        400: 'var(--scale-accent-400)',
        500: 'var(--scale-accent-500)',
        600: 'var(--scale-accent-600)',
        700: 'var(--scale-accent-700)',
        800: 'var(--scale-accent-800)',
        900: 'var(--scale-accent-900)',
      },
      error: {
        100: 'var(--scale-error-100)',
        200: 'var(--scale-error-200)',
        300: 'var(--scale-error-300)',
        400: 'var(--scale-error-400)',
        500: 'var(--scale-error-500)',
        600: 'var(--scale-error-600)',
        700: 'var(--scale-error-700)',
        800: 'var(--scale-error-800)',
        900: 'var(--scale-error-900)',
      },
      warning: {
        100: 'var(--scale-warning-100)',
        200: 'var(--scale-warning-200)',
        300: 'var(--scale-warning-300)',
        400: 'var(--scale-warning-400)',
        500: 'var(--scale-warning-500)',
        600: 'var(--scale-warning-600)',
        700: 'var(--scale-warning-700)',
        800: 'var(--scale-warning-800)',
        900: 'var(--scale-warning-900)',
      },
      success: {
        100: 'var(--scale-success-100)',
        200: 'var(--scale-success-200)',
        300: 'var(--scale-success-300)',
        400: 'var(--scale-success-400)',
        500: 'var(--scale-success-500)',
        600: 'var(--scale-success-600)',
        700: 'var(--scale-success-700)',
        800: 'var(--scale-success-800)',
        900: 'var(--scale-success-900)',
      },
      info: {
        100: 'var(--scale-info-100)',
        200: 'var(--scale-info-200)',
        300: 'var(--scale-info-300)',
        400: 'var(--scale-info-400)',
        500: 'var(--scale-info-500)',
        600: 'var(--scale-info-600)',
        700: 'var(--scale-info-700)',
        800: 'var(--scale-info-800)',
        900: 'var(--scale-info-900)',
      },
    },
    extend: {
      transitionDuration: {
        30: '30ms',
      },
      borderRadius: {
        'size-sm': defaultTheme.borderRadius.DEFAULT,
        'size-md': defaultTheme.borderRadius.md,
        'size-lg': defaultTheme.borderRadius.md,
        'size-xl': defaultTheme.borderRadius.md,
      },
      fontSize: {
        'size-sm': defaultTheme.fontSize.xs,
        'size-md': defaultTheme.fontSize.base,
        'size-lg': defaultTheme.fontSize.lg,
        'size-xl': defaultTheme.fontSize.xl,
        'h1': defaultTheme.fontSize['5xl'],
        'h2': defaultTheme.fontSize['3xl'],
        'h3': defaultTheme.fontSize['xl'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
