guidelines:
	pdflatex thesis
	pdflatex thesis
	bibtex thesis
	makeindex thesis
	makeglossaries thesis
	pdflatex thesis
	pdflatex thesis
clean:
	rm *.log *.aux *.dvi *.lof *.lot *.bit *.idx *.glo *.bbl *.bcf *.ilg *.toc *.ind *.out *.blg *.fdb_latexmk *.fls *.thm *.gz *.pdf
